name: Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 77.37.37.73
          username: u344800990.aldancare.com
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: /domains/aldancare.com/public_html/tasks/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
